### ISSUE TITLE
error when install with docker

### ISSUE THREAD

**Issue by previousdeveloper** [amrtgaber/angular2-cli-webpack-docker#1]
> execSync@1.0.2 install /usr/local/lib/node_modules/angular-cli/node_modules/execSync
> node install.js

The command '/bin/sh -c npm install --global angular-cli' returned a non-zero code: 1

**Comment by amrtgaber** [comment]
I just updated the angular-cli version. Could you pull and try again? If you get the error again, could you run `ng --version` and paste the output?

**Comment by previousdeveloper** [comment]
I am getting same error ?

**Comment by amrtgaber** [comment]
I'll need some more information to help.

What is your operating system?
What version of docker are you using?
When the build fails what are the last ~100 lines of console output (npm will usually give some more detail than the final docker error)?

**Comment by amrtgaber** [comment]
Closing this issue from lack of response.
